### ISSUE TITLE
Análisis de dependencias de CUMPLIDOS DVE

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#1]
Se requiere realizar el análisis de dependencias con las que actualmente cuenta el sistema de CUMPLIDOS DVE en ADMINISTRATIVA. Se deben identificar los servicios que se manejan, las APIs que se consumen y verificar si estas conexiones se van a manetener en la nueva versión del sistema o si se requieren consumir otras APIs.

**Criterios de aceptación**

- [ ] Listado de APIs y servicios consumidos y que consumen a cumplidos DVE.

Nota: tomar como referencia 
1. https://docs.google.com/spreadsheets/d/1oQ48wzCJZtPQLXsvFY8KPlIYzIFviLBX/edit?usp=sharing&ouid=104124925692794756698&rtpof=true&sd=true
2. https://docs.google.com/spreadsheets/d/14mORmhV7_eAZ8xB1XN02JPl_e6dieH6aWk6gwDB1BMo/edit?usp=sharing

**Comment by Mechaz123** [comment]
Se realiza el seguimiento a las API's que consume cumplidos DVE

Se adjunta el link del documento: https://docs.google.com/spreadsheets/d/1fnedMC2nQLPiQ88puWexQ0-CAFiYKwTV/edit?usp=sharing&ouid=117272980466294232560&rtpof=true&sd=true

**Comment by Mechaz123** [comment]
Se realiza una reevaluación de las API's que consume cumplidos DVE

Se adjunta el link del documento:
https://docs.google.com/spreadsheets/d/1fnedMC2nQLPiQ88puWexQ0-CAFiYKwTV/edit?usp=sharing&ouid=117272980466294232560&rtpof=true&sd=true

**Comment by a52290451** [comment]
Queda pendiente corrección de análisis de APIs

**Comment by Mechaz123** [comment]
Se realiza la corrección de análisis de API's, se adjunta al Excel del mismo link
