### ISSUE TITLE
Despliegue en producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#105]
Se requiere realizar la salida a producción de todas las funcionalidades desarrolladas en cumplidos DVE a la fecha, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2 - D
- [x] Revisión y actualización de variables de entorno - D
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo) - D
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL) - D
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento técnico - D

**Nota:** Este sistema no tiene creado un ambiente de producción para las APIs MID y CRUD y para el Cliente, por lo que se requiere iniciar con la solicitud de su creación.

**Comment by a52290451** [comment]
Solicitud de despliegue del cliente en ambiente de producción

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53231

**Comment by a52290451** [comment]
Actualización del swagger en cumplidos_dve_mid para pruebas y producción, realizada el 8 de mayo de 2023:

https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=CumplidosDVEMid&version=v1&provider=admin&tenant=carbon.super

**Comment by a52290451** [comment]
Solicitud de creación de esquema "cumplidos_dve" en BD udistrital_administrativa en producción y ejecución de Script en "parametros":

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53250&group_id=177

**Comment by a52290451** [comment]
Solicitud de registrar de variables en parameter store para el api "cumplidos_dve_crud" en ambiente de Producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53251&group_id=177

**Comment by a52290451** [comment]
Solicitud de despliegue de API cumplidos_dve_crud en ambiente de producción

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53248

**Comment by a52290451** [comment]
Solicitud de despliegue de cumplidos_dve_mid en ambiente de producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53253

**Comment by a52290451** [comment]
Plantilla de Manual técnico: 
[E-03- Aprobación de entregable Funcionamiento (1).docx](https://github.com/udistrital/cumplidos_dve_cliente/files/11466177/E-03-.Aprobacion.de.entregable.Funcionamiento.1.docx)

Manual técnico guía: 
[Descripción técnica Evaluaciones.docx](https://github.com/udistrital/cumplidos_dve_cliente/files/11466198/Descripcion.tecnica.Evaluaciones.docx)

**Comment by a52290451** [comment]
Se comprueba funcionamiento del API cumplidos_dve_mid en producción a través del healtcheck y del 
 GET - aprobacion_pago/dependencia_ordenador/52310001:

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/a55e57c7-414a-4a3e-8ffe-4760aae24653)

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/c5f2099e-3ac9-463b-ba1d-5ce9e9c29042)

**Comment by a52290451** [comment]
Se termina de comprobar el funcionamiento de cumplidos_dve_crud en producción con acceso a la base de datos.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/8c96ec8f-ac17-4624-b6c7-93ce352f999c)

**Comment by a52290451** [comment]
Se realiza solicitud de actualización de variables de entorno en cumplidos_dve_mid en ambiente de producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=53435

**Comment by a52290451** [comment]
Pruebas funcionales del sistema:

#99

**Comment by a52290451** [comment]
Pruebas de carga y seguridad:

#114

**Comment by a52290451** [comment]
Se realizan correcciones de pruebas de carga, estrés y seguridad en:

1. #114

**Comment by Mechaz123** [comment]
Se desarrolla el manual técnico relacionado a cumplidos DVE:
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/daarojasg_udistrital_edu_co/ETpqKLRaJ0FOuVrphRqieo0BMKQfKNKUQZOrRpTZqgZS1g?e=nwJfZ8

**Comment by a52290451** [comment]
Manuales de usuario relacionados:

1. [Manual de Ordenador del gasto](https://tinyurl.com/58s54u5h).
2. [Manual de Supervisor](https://tinyurl.com/3w7puww9).
3. [Manual Coordinador](https://tinyurl.com/289p3h5x).
4. [Manual de Docente](https://ti.udistrital.edu.co/sites/default/files/documentacion/2023-05/Solicitud%20Cumplidos%20(Docentes).pdf).

**Comment by Mechaz123** [comment]
@milo19980525 respondiendo a las preguntas:

- **¿En dado caso que un cumplido se apruebe por ordenador pero se desee reversar se haría por soporte?**
Repuesta: El sistema actualmente no cuenta con ninguna función de rollback para devolver dichos cambios, por lo cual si, se tendría que realizar la petición con soporte y realizar el cambio a nivel de BD

- **¿Si se cambia de ordenador o supervisor se asignan automáticamente las solicitudes a las nuevas personas a cargo?**
Repuesta: Si el cambio se hace en la tabla de pago_mensual, especificamente en el campo "responsable", si se asignarian a esa nueva persona

**Comment by Mechaz123** [comment]
Se realizan las correcciones requeridas al documento, este se sigue manteniendo bajo el mismo link

**Comment by Mechaz123** [comment]
Se desarrollan las pruebas unitarias para CUMPLIDOS_DVE_CRUD.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/24466c92-a9fd-4f20-88f7-940e1414e59f)

Y también las pruebas para CUMPLIDOS_DVE_MID.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/e46f9371-cb45-48a7-9ca7-225444b9b5fe)

Cabe aclarar que la única prueba en la que falla es la de default que viene creada desde mucho antes.

**Comment by Mechaz123** [comment]
Se realiza el cambio en el rol de Coordinador y Ordenador del Gasto, para el tema de la generación de certificados, ya que mientras se realizaban las pruebas unitarias se evidenció que existía un error en la validación de los pagos mensuales, por lo cual ya se realiza la corrección de dicho error.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/ed3ac076-1f6f-448f-aac1-b069e8212748)

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/9dfaa7d5-808e-4e4b-9b7e-9e8601a9c619)

**Comment by norbeydanilo** [comment]
@milo19980525 Por favor revisar estado de issue y dar cierre. Gracias
