### ISSUE TITLE
Desarrollo de lógica necesaria para replicar información de cumplidos aprobados para pago a titan_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#109]
Se requiere implementar lógica para replicar información de cumplidos aprobados para pago por parte del ordenador del gasto, a titan_mid.

**Especificaciones técnicas**

- El endpoint en titan_mid para replicar información es: http://pruebasapi.intranetoas.udistrital.edu.co:8082/v1/contrato_preliquidacion/cumplido_rp/ano/mes/contrato/vigencia/rp
- La información de RP y Vigencia RP debe consultarse de Resoluciones V2
- El último desarrollo de cumplidos dve se encuentra en la rama develop

**Sub Tareas**

- [x] Desarrollo de lógica para replicar información de cumplidos aprobados para pago de cumplidos_dve_mid a titan_mid.

**Criterios de aceptación**

- [x] Si un cumplido es aprobado por el ordenador del gasto, la información de este debe replicarse en titan_mid para que se actualice su estado.

**Requerimientos**

- No presenta requerimientos para su inicio.

**Dependencias**

- titan_mid
- resoluciones_crud_v2

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se desarrolla la funcionalidad asociada para el envío de la información de los cumplidos a TITAN

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/20edfdf0-fea8-4210-9d13-bf6f1cb0babd)

Se tuvieron dificultades para el tema de envío de titan, ya que primero se debe de enviar la información y después actualizar el estado del cumplido, y a la vez la validación cuando el envío de información a titan falla, como lo son casos donde el contrato no existe en la data de titan

**Comment by Mechaz123** [comment]
Se realiza el envío del Pull Request(https://github.com/udistrital/cumplidos_dve_cliente/pull/113) para subir los cambios al ambiente de pruebas
