### ISSUE TITLE
Correcciones requeridas

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#111]
Para la entrega de cumplidos_dve en su primer alcance, se requieren realizar las siguientes correcciones:

1. Implementación y pruebas de autenticación por Outlook (se requiere cruzar y sincronizar información de usuarios registrados en WSO2 y en el sistema de gestión académica - Red de datos).
2. Actualizar icono en el navegador al de cumplidos dve.
3. Insertar manual de usuario en página de presentación de cumplidos dve.
4. Realizar cambio de endpoint terceros_crud por autenticacion_mid para consultar información basica del usuario registrado en el sistema.
5. Ocultar botón de "ver soportes".
6. Revisar la solicitud de cumplido del mes de diciembre.

**Especificaciones técnicas**

- El endpoint de autenticacion_mid para consultar información basica del usuario por el correo registrado es: 
http://pruebasapi.intranetoas.udistrital.edu.co:8110/v1/token/userRol
- El desarrollo del cambio de endpoint debe subirse en una rama feature aparte y no subirse a release hasta nuevo aviso.
- Para autenticación por Outlook, se requiere habilitar esta opción en WSO2 y probar.

**Sub Tareas**

- [x] Sincronización de usuarios en WSO2 asociados a usuarios de cumplidos DVE.
- [x] Habilitar opción de autenticación por Outlook y realizar pruebas.
- [x] Actualización de icono de cumplidos dve en el navegador.
- [x] Insertar manual de usuario en página de presentación de cumplidos dve.
- [x] Desarrollo de lógica para cambiar endpoint de consulta de información basica de usuarios logueados.
- [x] Ocultar el botón "ver soportes".
- [x] Revisar la solicitud de cumplido del mes de diciembre.

**Criterios de aceptación**

- [x] Los usuarios de cumplidos DVE pueden ingresar al sistema, con su respectivo rol, a través de la autenticación por Outlook.
- [x] El icono del modulo de cumplidos DVE, aparece en el navegador.
- [x] El manual de usuario del modulo de cumplidos DVE, aparece en la pagina principal de precentación, posterior al login.
- [x] La consulta de información basica del usuario logueado en el modulo, se realiza por su correo electrónico a través del API autenticacion_mid.
- [x] No se observa el botón "Ver soportes".
- [x] Permite la carga de solicitud de cumplidos mes de diciembre.

**Requerimientos**

- [x] Manual de usuario.
- [x] Estrategia de sincronización de registros entre WSO2 y el sistema de gestión académica.

**Dependencias**

- autenticacion_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
De acuerdo a conversaciones con el Arquitecto relacionadas con la autenticación de cumplidos dve a través de WSo2, se acuerda:
1. El módulo de cumplidos debe mantener la autenticación por WSO2.
2. Los usuarios que no se encuentren registrados correctamente en WSo2, serán remitidos a la red de datos para obtener la información faltante y completar el registro.

**Comment by Mechaz123** [comment]
Se desarrolla las diferentes solicitudes dentro de las cuales se encuentra:

- La presentación de los manuales de usuarios según su rol, el cambio de endpoint para consultar la información de los usuarios logueados

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/f7bfe340-11bd-4981-a1f8-1dc6e9dad76b)
