### ISSUE TITLE
Correcciones consulta de cumplidos DVE

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_dve_cliente#121]
Se requiere verificar el flujo de cumplidos completo, teniendo en cuenta la integración con el sistema de resoluciones v2. 

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama release, tanto para el cliente como para las APIs mid y crud.
- La versión de resoluciones v2 estable se encuentra en release.

**Sub Tareas**

- [x] Verificación del flujo completo de cumplidos con un docente al que se le haya creado un contrato por resolciones v2.
- [x] Corrección de bugs y hallazgos encontrados.

**Criterios de aceptación**

- [x] Todas los bugs y hallazgos fueron corregidos.

**Requerimientos**

- Ninguno.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realizan pruebas de interoperabilidad  y se realiza la siguiente retroalimentación, de las correcciones necesarias:

- Corrección de fechas: adición de horas
- Certificado de coordinación: No aparecen los proyectos curriculares.
- Certificado ordenador: no genera bien el certificado.

**Comment by Mechaz123** [comment]
Con respecto a la corrección de fechas, se desarrolla la solución para el tema de la zona horaria de manera que ya se permite crear los cumplidos por parte del docente.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/ddb4c097-2f39-4a44-9b62-9a3e1d806d75)

Para el error de certificado de coordinación ya se visualizan los proyectos curriculares, el error se presentaba al momento de redireccionar a pruebas.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/93f32c0b-3e12-4019-9a1d-befc1ff653b4)

Para el certificado del ordenador, no existía data de busservicios para pruebas, directamente se consultaba de producción, por lo cual no coincidía la data para generar el certificado.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/1c074c4a-1b77-4ad7-b623-6c3f20e81ba7)

En base a lo anterior solo se realizaron cambios a nivel de código para el tema de las fechas.
