### ISSUE TITLE
Revisión de ejecución de primer alcance en local apuntando a producción todos los endpoints

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_dve_cliente#127]
Se requiere revisar minuciosamente la ejecución del MVP de cumplidos dve en producción.

**Especificaciones técnicas**

- El último despliegue del primer alcance se encuentra en la rama release

**Sub Tareas**

- [x] Revisar todos los endpoints apuntando a ambiente de producción.
- [x] Revisar data que falte por ser añadida en el ambiente de producción (parámetros, gestor documental, etc).
- [x] Verificación del cliente en producción (que responda).
- [x] Realizar scripts de borrado para que Jeisson los ejecute una vez desplegado en producción y probado el primer alcance
- [x] Revisar todo el flujo desde local con todos los endpints de producción.

**Criterios de aceptación**

- [x] Se evidencia en el issue las pruebas realizadas.
- [x] Se documentan los fallos que se presentan o tareas que faltan por hacer.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- todas las del prouecto

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Revisión de endpoints y disponibilidad de data en ambiente de producción.

Docentes:

1. Carga documentos docente
**cumplidos_dve_mid: informacion_academica/cargar_contratos_docente**

- http://api.intranetoas.udistrital.edu.co:8104/v1/informacion_proveedor/?query=num_documento:19188722
- http://api2.intranetoas.udistrital.edu.co:8528/v1/vinculacion_docente/?query=PersonaId:19188722&limit=-1

No se puede avanzar en las pruebas ya que no hay vinculaciones en resoluciones v2 actualmente.

2. Creación cumplidos docente
**cumplidos_dve_crud: pago_mensual**

- http://api2.intranetoas.udistrital.edu.co:8534/v1/pago_mensual/?query=numero_contrato:DVE135,vigencia_contrato:2023&limit=-1

No devuelve data ya que no hay pagos realizados. No hay registros.

**administrativa_amazon_api: acta_inicio**

- http://api.intranetoas.udistrital.edu.co:8104/v1/acta_inicio/?query=numero_contrato:DVE135,vigencia:2023 

**cumplidos_dve_crud: pago_mensual**

- http://api2.intranetoas.udistrital.edu.co:8534/v1/pago_mensual/?query=numero_contrato:DVE135,vigencia_contrato:2023,Mes:2,Ano:2023

No devuelve data ya que no hay pagos realizados ni cumplidos para ese mes. No hay registros.

- http://api.intranetoas.udistrital.edu.co:8510/v1/parametro/?query=codigo_abreviacion:CD_DVE,Nombre:CARGANDO DOCUMENTOS
- POST: http://api2.intranetoas.udistrital.edu.co:8534/v1/pago_mensual

**cumplidos_dve_mid: informacion_academica/informacion_coordinador**

- http://api2.intranetoas.udistrital.edu.co:8533/v1/informacion_academica/informacion_coordinador/72
- http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/servicios_homologacion_dependencias/proyecto_curricular_oikos/72
-

**Comment by a52290451** [comment]
De acuerdo a la revisión de endpoints, los ajustes requeridos son:

1. Actualización de variable de entorno CUMPLIDOS_DVE_MID_ACADEMICA_JBPM, pasando de "academica_produccion" a "servicios_academicos" en producción.

**Comment by a52290451** [comment]
Revisando a fondo el endpoint señalado: 

Se verificó que se encontraba mal redactada la información relacionada al mes, en vez de pasar 7, se debía pasar 07:

http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/administrativa_produccion/contratos_ordenador_dependencia/14/2023-07/2023-07

Con esto ya responde correctamente

**Comment by a52290451** [comment]
Se realiza actualización de variables de entorno en producción:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=54777

**Comment by a52290451** [comment]
Se realiza la corrección de un problema encontrado en la generación de certificados por parte del coordinador, el cual no permitía analizar todos los estados en los cuales se consideraba aprobado un cumplido y, por consiguiente, aparecía como no aprobado en el certificado generado.

El error se corrige ajustando la lógica de consulta de estados en cumplidos_dve_mid:

https://github.com/udistrital/cumplidos_dve_mid/pull/94

**Comment by a52290451** [comment]
Los demás ajustes requeridos, señalados previamente, se resuelven en:

https://github.com/udistrital/cumplidos_dve_mid/pull/74

**Comment by milo19980525** [comment]
Muchas gracias @a52290451 y @Mechaz123, por favor @Mechaz123 adjuntar script de borrado para ambiente de producción y  @a52290451 solicitar borrado de datos de producción una vez este se suba.

**Comment by a52290451** [comment]
Se realiza solicitud de borrado de datos asociados a cumplidos_dve:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=54843
