### ISSUE TITLE
Correcciones o ajustes salida a producción primer alcance

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_dve_cliente#128]
Se requiere realizar ajustes o correcciones necesarias para salida a prod primer alcance.

**Especificaciones técnicas**

- El último despliegue del primer alcance se encuentra en la rama release

**Sub Tareas**

- [x] En cumplidos_dve_mid, se requiere ajustar la función "ObtenerInfoOrdenador" ubicada en el helper "pago" para que la lógica de control solo permita consultar contratos de tipo 2, 3 y 18, y en el caso contrario, arroje un mensaje de error.
- [x] Se requiere realizar migración de usuarios y ajuste automático de Roles en WSo2.
- [x] En cumplidos_dve_cliente, realizar control de error al enviar la solicitud de cumplido por parte del docente al coordinador. Actualmente, cuando se envía la solicitud y falla la consulta del coordinador, no se notifica al docente el fallo del envío de la solicitud.
- [x] Actualmente, no existe una política de actualización de roles para usuarios cuando estos cambian de cargo. Se requiere consultar con Jhon el estado actual de esta actividad.

**Criterios de aceptación**

- [x] Se documentan correcciones realizadas y prueba de funcionamiento.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- administrativa_amazon_api

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by a52290451** [comment]
Correcciones requeridas:

- En cumplidos_dve_mid, se requiere ajustar la función "ObtenerInfoOrdenador" ubicada en el helper "pago" para que la lógica de control solo permita consultar contratos de tipo 2, 3 y 18, y en el caso contrario, arroje un mensaje de error.
-  Se requiere realizar migración de usuarios y ajuste automático de Roles en WSo2.
- En cumplidos_dve_cliente, realizar control de error al enviar la solicitud de cumplido por parte del docente al coordinador. Actualmente, cuando se envía la solicitud y falla la consulta del coordinador, no se notifica al docente el fallo del envío de la solicitud.
- **Actualmente, no existe una política de actualización de roles para usuarios cuando estos cambian de cargo.**

**Comment by Mechaz123** [comment]
Se realiza el cambio en el código de cumplidos_dve_mid, quitando la consulta que se hacía cuando no entraba al if del tipo contrato para valores 2, 3 y 18, ahora se dejará con un panic.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/efb7b8e4-6f45-4800-bb48-ef359d2ea7f6)

**Comment by Mechaz123** [comment]
Se realiza la corrección para mostrar un mensaje el cual notifique que no se pudo consultar la información del coordinador.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/a414bf6b-2ea8-4f87-8ab1-79e650f9a627)

**Comment by a52290451** [comment]
Se verifica el funcionamiento completo del sistema en producción a falta de la aprobación de cumplidos para pago y generación del certificado por parte del ordenador del gasto.

A continuación se muestran imágenes de su funcionamiento:

**DOCENTES**

1. Vista "Solicitud cumplidos docentes"

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/8fa2ea69-966b-4681-91d3-581ed5ec8aa4)

- Se carga correctamente la información del contrato asociado al docente
- Se carga correctamente la información personal del docente.

2. Vista "Solicitar cumplido"

- Se carga correctamente la información personal del docente.
- Se carga correctamente la información de los cumplidos enviados y los que se encuentran en tramite.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/0cc51614-5405-4592-91a3-7f20b2366cf1)

- Cuando se intenta generar un cumplido para un mes que ya tiene uno creado, arroja la alerta correctamente.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/2c1db3b1-93fe-4e7b-bf36-7307a2f143d8)

- Permite crear un cumplido para un mes que no tiene cumplidos creados y habilita la opción para enviarlo a revisión.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/e1ef2f3b-da1a-4bb8-8468-7dc89957c7c0)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/f5581b7f-5aee-4378-917d-9ca3eb3fb661)

- Permite enviar el cumplido para su revisión por parte del coordinador y actualiza su estado.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/ef11f2b6-6168-4097-b641-dc5d5e431eb1)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/97680e56-5cf2-4033-ae4a-86d343394e0a)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/81f38395-ca7e-460e-86ed-0c82836b9ca8)

**COORDINADOR**

1. Vista "Aprobación coordinador"

- Carga correctamente la información del coordinador.
- Carga correctamente la información de los cumplidos asociados al coordinador, disponibles para su revisión.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/d361fa09-bbea-4633-8f59-a0e034c059db)

- Permite generar el certificado correspondiente, señalando los campos obligatorios. En este caso, para el contrato DVE3269, como no se a aprobado, aparece como no aprobado en el certificado.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/9dabe623-4537-4fc2-b2d3-35e6ec909b0e)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/6293c2e5-dff3-4e67-961b-da755b23b446)

- Permite aprobar o rechazar un cumplido y actualiza su estado de acuerdo a la acción realizada.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/991e89d9-ea01-4757-821f-6ea876b5a80e)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/e1423e30-da8e-4260-b16f-9a477dae2949)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/76bff7d0-1e25-4a3e-955e-bd6ca9021688)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/683144b3-79e9-4415-82a0-1f763846a4d5)

- Si se genera nuevamente el certificado, ya no aparece el contrato DVE3269 como "no aprobado".

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/54e442f3-8a8f-4626-9f67-42e89957f012)

**SUPERVISOR**

1. Vista "Aprobación supervisor"

- Carga correctamente la información del supervisor.
- Carga correctamente la información de los cumplidos asociados al supervisor, disponibles para su revisión.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/15a81fcd-0a5c-4066-b59b-ea5b3b2d7ca3)

- Permite aprobar o rechazar un cumplido y actualiza su estado de acuerdo a la acción realizada.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/3b1fb55e-ce41-476c-940f-bc647ba833d7)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/4800c044-98c4-4b01-8837-b463e4d4f163)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/c190716c-89a2-41a2-ac8e-08d4464c30d1)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/30cbe1dc-9571-495c-8114-7a91d806b7fa)

**ORDENADOR DEL GASTO**

1. Vista "Aprobación pago"

- Carga correctamente la información del ordenador del gasto.
- Carga correctamente la información de los cumplidos asociados al ordenador del gasto, disponibles para su revisión.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/22321b6f-57fb-41cf-8779-065791356706)

- Permite generar el certificado correspondiente, señalando los campos obligatorios. En este caso, para el contrato DVE3269, como no se a aprobado, aparece como no aprobado en el certificado.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/488db6ad-6aed-4dc1-8117-e549e35a2c2a)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/dab5d3fa-0615-4baa-9f3d-67d31cfe2f19)

- Permite aprobar o rechazar uno o varios cumplidos y actualizar su estado de acuerdo a la acción realizada.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/cbc2f99e-f222-45d1-a333-f4a054686b57)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/bacf109f-33bc-485e-aa6e-a2634da0db0a)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/b9806377-fcda-4616-ba47-05d36b9c83c4)
![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/36229498/230884d6-289e-416a-a498-65b323535445)

**Nota:** En este caso no es posible probar la aprobación del pago de un cumplido ya que esto causaría cambios en otros sistemas.

**Comment by a52290451** [comment]
Se envía correo a la red de datos, solicitando completar el archivo de usuarios para realzar su respectiva migración a WSo2:

[Correo_ BRAYAN LEONARDO SIERRA FORERO - Outlook.pdf](https://github.com/udistrital/cumplidos_dve_cliente/files/12196944/Correo_.BRAYAN.LEONARDO.SIERRA.FORERO.-.Outlook.pdf)

**Comment by a52290451** [comment]
Se da por finalizado las correcciones requeridas en cumplido_dve_mid. El sistema se encuentra estable en producción y está listo para su utilización por parte de los diferentes roles.

Nota: queda pendiente completar la migración de usuarios.

**Comment by norbeydanilo** [comment]
La migración de usuarios se encuentra demorada por el incidente de seguridad presentado en la semana. El jefe está al tanto de este ítem para el adecuado funcionamiento del sistema.

**Comment by norbeydanilo** [comment]
Respecto al enlace en SGA se tendrá sesión para ello el 8/8/23

**Comment by norbeydanilo** [comment]
@milo19980525 Por favor revisar estado de issue y dar cierre. Gracias
