### ISSUE TITLE
HU1 - 1 - MockUps para vista de "Carga Documentos docentes".

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#13]
Con base en la vista de "Carga Documentos Docentes" del sistema "Admistrativa" y en las [historias de usuario](https://docs.google.com/spreadsheets/d/1k5OZ54PjV7v8eE5nqK-rZYd-ki-a4GYM/edit#gid=1984585544), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Mensaje de Alerta que indica que el contratista no cuenta con contratos asociados.
2. Vista de "Carga Documentos Docentes".

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se plante el siguiente bosquejo para la sección de Carga Documentos Docente:

![Carga_documentos_docentes](https://user-images.githubusercontent.com/73924638/206626463-52270f28-3731-423e-b9cf-8e54044f52b2.png)

**Comment by a52290451** [comment]
Se aprueban mockups propuestos.

Nota: ajustar colores a paleta de colores de administrativa
