### ISSUE TITLE
Documento Diagnóstico Final

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_dve_cliente#139]
Se requiere realizar el documento final "Diagnóstico" para todos las funcionalidades desarrolladas y por desarrollar en Cumplidos Docente v2.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.

**Sub Tareas**

- [ ] Con base en el formato propuesto desarrollar el informe.

**Criterios de aceptación**

- [ ] Se genera un diagnóstico final sobre los proyectos llevados a cabo en Cumplidos Docente v2.

**Requerimientos**

- [X] Formato para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se sube el documento para su revisión.

[DIAGNOSTICO FINAL CUMPLIDOS DVE.docx](https://github.com/udistrital/cumplidos_dve_cliente/files/13420277/DIAGNOSTICO.FINAL.CUMPLIDOS.DVE.docx)

**Comment by milo19980525** [comment]
@Mechaz123 muy buen trabajo, dentro del plan de mejoramiento por favor mencionar lo que había quedado pendiente del segundo alcance.

**Comment by Mechaz123** [comment]
Se adjunta la limitación y plan de mejoramiento acerca de los soportes del sistema, adicionalmente se agrega una oportunidad de mejora con respecto a los filtros de información.

[DIAGNOSTICO FINAL CUMPLIDOS DVE.docx](https://github.com/udistrital/cumplidos_dve_cliente/files/13429625/DIAGNOSTICO.FINAL.CUMPLIDOS.DVE.docx)

**Comment by milo19980525** [comment]
@Mechaz123 perfecto, buen trabajo.
