### ISSUE TITLE
HU1 - 1 - Creación menú "Solicitud Cumplidos Docentes"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#14]
Se requiere la creación  del menú "Solicitud Cumplidos Docentes" asociado al rol de "Docente".

Pasos de creación:

1. Creación de sistema CUMPLIDOS_DVE en sistema "CONFIGURACIÓN"
2. Creación de menú "Solicitud Cumplidos Docentes" en "CONFIGURACIÓN" asociado a CUMPLIDOS_DVE.
3. Asignación de roles "Docente" y "Administrador" para visualizar el menú de Solicitud Cumplidos Docentes" en "CONFIGURACIÓN".
4. Llamado de menú "Solicitud Cumplidos Docentes" desde el cliente de cumplidos dve.

**Criterios de aceptación**

- [x] Creación y registro de menú "Solicitud Cumplidos Docentes" en Configuración.
- [x] Pruebas de visualización del menú "Solicitud Cumplidos Docentes".

Nota: [sistema Configuración en pruebas](https://pruebasconfiguracion.portaloas.udistrital.edu.co/)

**Comment by a52290451** [comment]
https://github.com/udistrital/cumplidos_dve_cliente/pull/20

**Comment by Mechaz123** [comment]
Se comprueba que el menú se puede visualizar en ambiente de pruebas 

![image](https://user-images.githubusercontent.com/73924638/207121951-bc4c8316-f185-4676-b6e9-079bb560b63c.png)

![image](https://user-images.githubusercontent.com/73924638/207121987-fdf9b1dd-5805-4123-86b7-e5135bf0cfd8.png)

**Comment by a52290451** [comment]
Se validan pruebas realizadas
