### ISSUE TITLE
Control de cambios RFC 59789 - Aprobación masiva de cumplidos de docente 

### ISSUE THREAD

**Issue by criss201x** [udistrital/cumplidos_dve_cliente#145]
## Descripción

Se identifica el incidente de que la aprobación masiva mediante el ckeck en la selección masiva de cumplidos de docentes de vinculación especial no estaba funcional en ninguna de las vistas de los roles ( coordinador, supervisor y decano)

## items a cambiar

Check de selección masiva para aprobación en todas las vistas(coordinador, supervisor y ordenador)

## Necesidad y justificación

**Necesidad:** Se hace necesario dejar funcional el check para seleccionar y aprobar de forma masiva las solicitudes de cumplidos dve.

**Justificación:** actualmente no se puede dar aprobaciones masivas selccioando varias solicitudes mediante el check impactando en los tiempos de esta actividad de forma negativa .

## Efectos de no implementar

De no implementarse los roles de coordinador, supervisor y decano tendrían que seguir seleccionando uno a uno y luego si aprobarlos masivamente.

## Plan de reversión

Regresar al Commit Anterior - Teniendo en cuenta que es un cambio de aplicación solo con regresar al commit anterior se estabilizara el Sistema en caso de errores., Aplicar backup de base de datos, Realizar un snapshot

## Actividades 

- [x] Enlazar en los comentarios commits relacionados a este desarrollo
- [x] Despliegue, documentar validación  inicial.
- [x] Despliegue, documentar validación  en ambiente de pruebas (release).
- [ ] Despliegue en ambiente de produccion.

## **Definition of Ready - DoR**

De acuerdo a lo estipulado en RFC tuleap 

## **Definition of Done - DoD - Desarrollo**

De acuerdo a lo estipulado en RFC tuleap

**Comment by aalejoz25** [comment]
Tener en cuenta el PR #144, pues alli se tienen en cuenta algunos detalles que no se alcanzaron a documentar en este issue.

**Comment by aalejoz25** [comment]
Tener en cuenta el PR #144 , pues alli se tienen en cuenta algunos detalles que no se alcanzaron a documentar en este issue.

**Comment by aalejoz25** [comment]
Se adjunta RFC de tuleap
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=59789

**Comment by aalejoz25** [comment]
Se hace la solicitud para pasar la funcionalidad de aprobacion multiple a produccion. para ello, tener en cuenta las siguientes considerciones:

1.) Al realizarse y aprobar, esta solo aprobará los cumplidos que esten en la pagina de la tabla que se esta visualizando, es decir, no se aprobaran absolutamente todos los cumplidos que esten asignados al usuario.

2.) Cuando se tienen seleccionados cumplidos en una pagina, si se hace el cambio de pagina no se tendran en cuenta los cumplidos previamente seleccionados, lo que quiere decir que solo se podran aprobar cumplidos que esten en la pagina de la tabla que se esté visualizando.

**Comment by aalejoz25** [comment]
Se realiza el merge en master para envio a producción
