### ISSUE TITLE
HU1 - 1 - Creación de logotipo Cumplidos DVE con base en logotipo Cumplidos

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#15]
Creación de logotipo para Cumplidos DVE con base en logotipo de Cumplidos Contratistas.

**Criterios de aceptación**

- [x] Creación y carga de logotipo en el issue.
- [x] Aprobación de logotipo.
- [x] Carga de logotipo en ambiente de pruebas.
- [x] Prueba técnica de visualización del logotipo.

Nota: el tamaño del logotipo debe ser igual al que se maneja en cumplidos contratistas.

**Comment by Mechaz123** [comment]
Se plantea el siguiente logo con base al de cumplidos:

![Cumplidos_DVE](https://user-images.githubusercontent.com/73924638/205573204-41fb9952-ed5d-4bea-924e-f2f79b61d446.png)

**Comment by Mechaz123** [comment]
Se plantea el logotipo para Cumplidos Docentes VE:

![Cumplidos_Docentes_VE](https://user-images.githubusercontent.com/73924638/205849560-878d3c3a-7482-49ac-847f-eeaf6617f01a.png)

**Comment by Mechaz123** [comment]
Se plantea el logotipo para Cumplidos Docentes Vinculación Especial:

![Cumplidos_Docentes_Vinculacion_Especial](https://user-images.githubusercontent.com/73924638/205852548-0abd5bff-0152-47a5-8a1e-0a910dec2d22.png)

**Comment by a52290451** [comment]
A sugerencia del área de arquitectura, se escoge la opción 3 del grupo de opciones registradas. Se debe ajustar paleta de colores de acuerdo a como se encuentra en administrativa.

**Comment by Mechaz123** [comment]
Se realiza la modificación solicitada con respecto a los colores del logo:

![Cumplidos_Docentes_Vinculacion_Especial_final](https://user-images.githubusercontent.com/73924638/206367447-ae44efdd-54b4-43aa-8340-8d973f07d220.png)

**Comment by Mechaz123** [comment]
Se carga el logotipo en ambiente de pruebas

![image](https://user-images.githubusercontent.com/73924638/206749093-bfa1bf89-4400-4f97-9f83-4b6a11226dd3.png)

**Comment by Mechaz123** [comment]
Se cambial a paleta de colores, para que concuerde con el logo

![image](https://user-images.githubusercontent.com/73924638/206757388-5815e74c-7e63-46eb-b902-295a635883c0.png)

![image](https://user-images.githubusercontent.com/73924638/206757427-a553fd02-3c1d-4143-ac38-e408a9830add.png)

**Comment by a52290451** [comment]
https://github.com/udistrital/cumplidos_dve_cliente/pull/20
