### ISSUE TITLE
Desarrollo controlador, modelos y helpers asociados a Informacion_academica en cumplidos_dve_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#21]
Se requiere migrar logica de desarrollo de administrativa_mid a cumplidos_dve_mid, asociada al controlador "informacion_academica". Las funciones relacionadas son:

- GetContratosDocente()
- ObtenerInfoCoordinador()

Se deben crear modelos de datos cuando se requieran, de acuerdo a cada función definida en el controlador.

Los Helpers deben crearse cuando se requieran y deben estar nombrados de acuerdo a la funcionalidad que abordan.

**Nota:** se debe optimizar la lógica de las funciones incluyendo Helpers si se requieren, eliminando código redundante y documentando el código desarrollado.

**Criterios de aceptación**

- [x] Dearrollo en local.
- [x] Pruebas en local.
- [x] Creación de rama feat con el desarrollo.
- [x] Commit en rama feat.
- [x] PR en develop
- [x] Check list de despliegue en ambiente de pruebas.
- [x] PR en release.
- [x] Pruebas funcionales.

**Comment by Mechaz123** [comment]
Se realizan pruebas en local con el id 28 y 72

![image](https://user-images.githubusercontent.com/73924638/207735162-7d3ba8de-0e4e-40c8-a6e8-838ae9f23ef3.png)

![image](https://user-images.githubusercontent.com/73924638/207735420-4fdf3285-4cfe-4370-8817-ebe1b9944c99.png)

**Comment by Mechaz123** [comment]
Se realizan pruebas en local con el número indicado, para el controlador de GetContratosDocente

![image](https://user-images.githubusercontent.com/73924638/208190416-c01bed45-889f-4bd3-8511-a4aa0c8ebd79.png)
