### ISSUE TITLE
Desarrollo controlador, modelos y helpers asociados a aprobacion_documentos en cumplidos_dve_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#22]
Se requiere migrar logica de desarrollo de administrativa_mid a cumplidos_dve_mid, asociada al controlador "aprobacion_documentos". Las funciones relacionadas son:

- GetSolicitudesSupervisor()
- GetSolicitudesCoordinador()
- AprobarMultiplesSolicitudes()
- CertificacionVistoBueno()
- AprobarDocumentos()

Se deben crear modelos de datos cuando se requieran, de acuerdo a cada función definida en el controlador.

Los Helpers deben crearse cuando se requieran y deben estar nombrados de acuerdo a la funcionalidad que abordan.

**Nota:** se debe optimizar la lógica de las funciones incluyendo Helpers si se requieren, eliminando código redundante y documentando el código desarrollado.

**Criterios de aceptación**

- [x] Dearrollo en local.
- [x] Pruebas en local.
- [x] Creación de rama feat con el desarrollo.
- [x] Commit en rama feat.
- [x] PR en develop
- [x] Check list de despliegue en ambiente de pruebas.
- [x] PR en release.
- [x] Pruebas funcionales.

**Comment by Mechaz123** [comment]
Se realiza prueba para obtener un 400 en inforrmacion_supervisor

![image](https://user-images.githubusercontent.com/73924638/209600721-4129feb7-6fbc-464b-97dd-10ac2b07114b.png)

**Comment by Mechaz123** [comment]
Se realiza prueba para obtener un 400 en solicitudes_coordinador

![image](https://user-images.githubusercontent.com/73924638/209602207-78fb1f23-c03d-4e1f-aac6-6756f306d456.png)

**Comment by Mechaz123** [comment]
Se realiza la prueba para certificacion visto bueno, de manera que nos retorna los resultados exitosos

![image](https://user-images.githubusercontent.com/73924638/209735320-60abf8e3-bab7-4450-a1e2-617ad38991da.png)

Se realiza la prueba para que retorne un 400 de manera que se valide el no encontrar datos

![image](https://user-images.githubusercontent.com/73924638/209735530-4743fe59-a542-4ddc-b9d7-8c3411b13135.png)
