### ISSUE TITLE
Desarrollo controlador, modelos y helpers asociados a Aprobacion_Pago en cumplidos_dve_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#23]
Se requiere migrar logica de desarrollo de administrativa_mid a cumplidos_dve_mid, asociada al controlador "aprobacion_pago". Las funciones relacionadas son:

- CertificacionDocumentosAprobados()
- PagoAprobado()
- GetSolicitudesOrdenador()
- ObtenerDependenciaOrdenador()
- AprobarMultiplesPagos()
- ObtenerInfoOrdenador()

Se deben crear modelos de datos cuando se requieran, de acuerdo a cada función definida en el controlador.

Los Helpers deben crearse cuando se requieran y deben estar nombrados de acuerdo a la funcionalidad que abordan.

**Nota:** se debe optimizar la lógica de las funciones incluyendo Helpers si se requieren, eliminando código redundante y documentando el código desarrollado.

**Criterios de aceptación**

- [x] Dearrollo en local.
- [x] Pruebas en local.
- [x] Creación de rama feat con el desarrollo.
- [x] Commit en rama feat.
- [x] PR en develop
- [x] Check list de despliegue en ambiente de pruebas.
- [x] PR en release.
- [x] Pruebas funcionales.

**Comment by Mechaz123** [comment]
Prueba a solicitudes ordenador, en este caso el ordenador no posee ninguna solicitud

![image](https://user-images.githubusercontent.com/73924638/209506935-fb4fb4b0-08b8-45e9-b7f6-b8b40b9b662c.png)

**Comment by Mechaz123** [comment]
Se prueba dependencia ordenador, con el fin de obtener un resultado exitoso

![image](https://user-images.githubusercontent.com/73924638/209590296-74ef7229-e115-4c60-b813-b04cfc728750.png)

**Comment by Mechaz123** [comment]
Se prueba información ordenador, aportando el número de contrato y la vigencia

![image](https://user-images.githubusercontent.com/73924638/209592839-2aadd100-bebd-4f3f-9f19-a0eb79dd632e.png)

**Comment by Mechaz123** [comment]
Se realiza la consultar para comprobar el pago aprobado, que nos debe de devolver un true, afirmando que el pago está hecho

![image](https://user-images.githubusercontent.com/73924638/209727680-34fcd8dc-8503-443b-a001-b1eb27da92a4.png)

Ahora debe de retornar un false al no encontrar el contrato, o algún dato proporcionado

![image](https://user-images.githubusercontent.com/73924638/209727794-71adb200-d36d-4a61-9562-4489292f4216.png)
