### ISSUE TITLE
HU1 - 1 - 1&2 - Desarrollo vista "Solicitud cumplidos docentes"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#24]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/13), se requiere implementar vista de "solicitud cumplidos docentes" en la cual se presente la lista de contratos asociados al docente junto con la casilla de su nombre.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se crea la vista en base al mockup realizado anteriormente

![image](https://user-images.githubusercontent.com/73924638/210686440-8696bd59-6534-46c4-8aed-972fd77cb69c.png)

Junto con la respectiva alerta planteada para el caso de no encontrar docentes asociados

![image](https://user-images.githubusercontent.com/73924638/210686143-242ce05a-9418-4d3a-b1f8-3c337567ec71.png)

**Comment by a52290451** [comment]
Despliegue en Develop: https://github.com/udistrital/cumplidos_dve_cliente/pull/35

**Comment by Mechaz123** [comment]
Para este caso, no se requiere actualizar el archivo checklist para cumplidos_dve_cliente
