### ISSUE TITLE
HU1 - 1 - 1&2 - Desarrollar lógica de vista "Solicitud cumplidos docentes" en el cliente

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#25]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/13) y la [vista desarrollada](https://github.com/udistrital/cumplidos_dve_cliente/issues/24), se requiere implementar lógica para carga de contratos e información del docente en vista de "solicitud cumplidos docentes" en la cual se presente la lista de contratos asociados al docente junto con la casilla de su nombre.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla la lógica de la vista Solicitud Cumplidos Docente

![image](https://user-images.githubusercontent.com/73924638/210686640-7cca1378-366c-4bdf-b668-e3dfe7725213.png)

**Comment by a52290451** [comment]
Despliegue en Develop: https://github.com/udistrital/cumplidos_dve_cliente/pull/35

**Comment by Mechaz123** [comment]
Para este caso, no se requiere actualizar el archivo checklist para cumplidos_dve_cliente
