### ISSUE TITLE
HU1 - 3 - 1 - MockUps para vista de "Creación_cumplidos_docente"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#27]
Con base en la vista de "Solicitar Cumplidos" del sistema "Admistrativa" y en las [historias de usuario](https://docs.google.com/spreadsheets/d/1k5OZ54PjV7v8eE5nqK-rZYd-ki-a4GYM/edit#gid=1984585544), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Mensaje de Alerta que indica que se deben completar los campos requeridos cuando haga clic en el boton "Crear Solicitud".
2. Se muestra mensaje emergente que indica que el cumplido seleccionado ya se encuentra registrado (Año y Mes).
3. Se muestra mensaje emergente con confirmación de creación de la solicitud.
4. Vista de "Creación_cumplidos_docente".

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se crea la alerta que indica que se deben completar los campos requeridos cuando haga clic en el boton "Crear Solicitud".

![image](https://user-images.githubusercontent.com/73924638/210921122-90807702-1a7e-4e77-a0bd-5d1053a954af.png)

Se crea la alerta que indica que el cumplido seleccionado ya se encuentra registrado (Año y Mes).

![image](https://user-images.githubusercontent.com/73924638/210921312-99273564-a618-41b7-954c-6b29ae2157a3.png)
