### ISSUE TITLE
HU1 -3 - 1 - Desarrollo vista "Creación_cumplidos_docente"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#28]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/27), se requiere implementar vista de "Creación cumplidos docente" en la cual se presente la opción para crear una solicitud de cumplido por mes y año y la lista de cumplidos asociados al docente tanto en proceso como terminados.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla la vista de creacion_cumplidos_docente

![image](https://user-images.githubusercontent.com/73924638/212777152-bbd11261-311b-47dc-8a3c-ab38378279d2.png)

![image](https://user-images.githubusercontent.com/73924638/212777359-0037f1c1-dd87-4bed-8faa-448fae172ffd.png)
