### ISSUE TITLE
HU1 - 3 - 1 - Desarrollar lógico de vista "Creación_cumplidos_docente"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#29]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/27) y la [vista desarrollada][(https://github.com/udistrital/cumplidos_dve_cliente/issues/24](https://github.com/udistrital/cumplidos_dve_cliente/issues/28), se requiere implementar lógica para creación y visualización de cumplidos de la vista "creación cumplidos docentes" en la cual se permite la creación de cumplidos por mes y año y se presenta la lista de cumplidos asociados al docente.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: en este issue no se requiere el desarrollo de las acciones permitidas por solicitud.

**Comment by Mechaz123** [comment]
Se desarrolla la lógica de creacion_cumplidos_docente

![image](https://user-images.githubusercontent.com/73924638/212777814-9b738b35-b577-4b97-b0d8-10199b8723e9.png)

![image](https://user-images.githubusercontent.com/73924638/212777826-70a22414-3606-449a-8c83-f339763e48a6.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de las pruebas funcionales:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwB3wNMix8-xZviQRmTko8hgw?e=FncmIS
