### ISSUE TITLE
HU1 - 4 - 1 - Desarrollo de lógica de control para campos requeridos en "creación_cumplidos_docente" para el botón "Crear Solicitud"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#30]
Se requiere implementar lógica de control asociada a los campos mes y año de la vista "Creación cumplidos docente", de tal forma que no se permita crear una solicitud de cumplido cuando dichos campos no se encuentren completos. La lógica debe estar asociada al botón "crear solicitud".

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se crea la lógica asociada a creacion_cumplidos_docente, con respecto a la alerta la cual debe de aparecer cuando los campos de Mes y año no están completos.

![image](https://user-images.githubusercontent.com/73924638/212778170-2c285562-3381-4b87-81f0-509ca8185a13.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq
