### ISSUE TITLE
HU1 - 4 - 2 - Desarrollo de lógica de validación para creación de solicitud de cumplido en vista de "creación_cumplidos_docente" asociada al botón "Crear Solicitud"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#31]
Se requiere implementar lógica de control asociada a los campos mes y año de la vista "Creación cumplidos docente", de tal forma que no se permita crear una solicitud de cumplido cuando la solicitud seleccionada ya se encuentre creada. La lógica debe estar asociada al botón "crear solicitud".

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se crea la logica asociada al botón Crear Solicitud, el cual debe de generar una alerta cuando exista el cumplido seleccionado.

![image](https://user-images.githubusercontent.com/73924638/212779366-30d1355d-02e8-40a0-99bc-00229aaffe51.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq
