### ISSUE TITLE
HU1 - 4 - 3 - Desarrollo lógica de creación de solicitud de cumplido en vista "creación_cumplidos_docente" asociada al botón "Crear Solicitud".

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#32]
Se requiere implementar lógica de creación asociada a los campos mes y año de la vista "Creación cumplidos docente", de tal forma que se registre y cree una solicitud de cumplido cuando se seleccione el botón "crear solicitud".

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se crea la lógica relacionada para realizar la inserción del cumplido y también se muestra una alerta de exito

![image](https://user-images.githubusercontent.com/73924638/212779738-552a00d3-1a40-4c93-bf3b-fad181baf04d.png)

![image](https://user-images.githubusercontent.com/73924638/212779766-98dd9836-b1e8-47ca-ac88-8cfbfde57b88.png)

![image](https://user-images.githubusercontent.com/73924638/212779794-c033f85f-2aeb-4080-8651-dc798c7bdb21.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq
