### ISSUE TITLE
HU1 - 5 - 1 - Desarrollo de lógica para cargar soportes en cuadro emergente asociado a la acción "Ver Soportes" de la columna "Acciones" del cuadro de solicitudes de cumplidos del docente.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#33]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/37) y la [vista desarrollada](https://github.com/udistrital/cumplidos_dve_cliente/issues/34), se requiere implementar lógica para creación y visualización del recuadro emergente, asociado a soportes de solicitudes de cumplidos. La lógica debe realizar una consulta a la base de datos de cumplidos dve y traer la información asociada a soportes de una solicitud en particular.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla el cuadro emergente relacionado con los soportes de los cumplidos, con información.

![image](https://user-images.githubusercontent.com/73924638/214159787-3475bf9d-6df7-42c3-8ed2-3289803167ff.png)

Sin Información.

![image](https://user-images.githubusercontent.com/73924638/214159895-5cf1a5a8-f19a-4320-8422-dd4459c86417.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq
