### ISSUE TITLE
HU1 - 5 - 1 - Desarrollo de cuadro emergente asociado a la acción "Ver Soportes" de la columna "Acciones" del cuadro de solicitudes de cumplidos del docente.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#34]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/37), se requiere implementar cuadro emergente para "Registro de soportes" asociados a una solicitud de cumplido, en el cual se listen todos los soportes cargados por el docente, asociados a una solicitud de cumplido.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza la creación del cuadro emergente llamado "Ver-Soportes"

![image](https://user-images.githubusercontent.com/73924638/213557409-d406c05d-b5af-4c20-b6e7-5cf6630c8615.png)
