### ISSUE TITLE
HU1 - 5 - 1 - Mockups para cuadro de soportes

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#37]
Con base en las [historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Cuadro emergente sin información de soportes.
2. Cuadro emergente con los soportes registrados por filas de la solicitud seleccionada.

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se crea el mockup cuadro emergente del soporte asociado al cumplido, sin informacion.

![image](https://user-images.githubusercontent.com/73924638/213059773-1884a4d1-9f6a-43bd-862e-0eadf1c07026.png)

**Comment by Mechaz123** [comment]
Se crea el mockup cuadro emergente del soporte asociado al cumplido, con informacion.
![image](https://user-images.githubusercontent.com/73924638/213061496-161acba5-885f-4101-a310-1bbb499887dc.png)
