### ISSUE TITLE
HU1 - 6 - 1 - Mockups para envio de solicitud de cumplido

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#39]
Con base en las [historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Mensaje de pregunta para creación de la solicitud.
2. Mensaje de confirmación de creación de la solicitud.
3. Boton o enlace con icono para enviar solicitud.

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se crea el Mockup relacionado al cuadro emergente de confirmación

![image](https://user-images.githubusercontent.com/73924638/214177294-c427aef6-1cda-47d5-ac27-73b3b4b2262f.png)

**Comment by Mechaz123** [comment]
Se crea el mockup para el botón enviar

![Boton_enviar](https://user-images.githubusercontent.com/73924638/214180741-1bda413d-7872-4c41-8777-beaa48be6e74.png)

**Comment by Mechaz123** [comment]
Mensaje de alerta de confirmación, cuando el cumplido ha sido enviado.

![image](https://user-images.githubusercontent.com/73924638/214434350-1e7f1a66-d915-4248-9bc4-939d4dde72fa.png)
