### ISSUE TITLE
Modelo de datos

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#4]
Tareas asociadas al modelo de datos:

1. Diseño de modelo de datos con base en tablas relacionadas en administrativa.

2. Validación y correcciones del modelo de datos.

**Criterios de aceptación**

- [x] Creación de modelo de datos en PG Modeler.

nota: link de descar de [PGModeler ](https://www.mediafire.com/file/5uug5blfm5gs2rm/pgmodeler-portable.rar/file)

**Comment by Mechaz123** [comment]
Se agrega el modelo de datos planteado para cumplidos DVE

![image](https://user-images.githubusercontent.com/73924638/201411448-f5110ee0-80e0-4772-965e-f63cfa319c0b.png)

Queda a la espera de revisión, para correcciones, dado el caso

**Comment by a52290451** [comment]
Se requiere realizar corrección de diagrama de datos, eliminando tablas paraméticas.

**Comment by Mechaz123** [comment]
Se realiza la corrección mencionada, de manera que se eliminan las dos tablas parametricas y se agrega la aclaración de los cambios

![image](https://user-images.githubusercontent.com/73924638/201970201-1fd68e8f-5cc3-4b4d-a7e5-ddd9464d72e6.png)

**Comment by Mechaz123** [comment]
Se realiza la modificación con respecto al tipo de datos y algunas aclaraciones de dos tablas que se encuentran en otra base de datos

![image](https://user-images.githubusercontent.com/73924638/202011029-93b31081-0ef5-42d3-b56f-300b42854ed6.png)

**Comment by Mechaz123** [comment]
Se realizan las respectivas modificaciones a al modelo de base de datos para cumplidos dve
![image](https://user-images.githubusercontent.com/73924638/202355319-b7a4d7a5-bb5a-4ac5-96f2-9765f78c1a9f.png)

**Comment by Mechaz123** [comment]
Se realiza varias correcciones con respecto a administrativa_jbpm

![image](https://user-images.githubusercontent.com/73924638/202554308-af1a6714-edd8-4487-8d97-3219ef2bb6d0.png)

**Comment by a52290451** [comment]
Se aprueba modelo de datos.
