### ISSUE TITLE
HU1 - 6 - 1 - Desarrollo de lógica para envio de solicitudes de cumplidos

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#40]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/39) y la [vista desarrollada](https://github.com/udistrital/cumplidos_dve_cliente/issues/28), se requiere implementar lógica para envio de solicitud de cumplido a través de la acción "Enviar solicitud" del conjunto de acciones habilitadas para dicha solicitud. La acción debe estar habilitada cuando la solicitud se encuentre en estado "RECHAZADA" o "CARGANDO DOCUMENTOS". 

Nota: tomar como referencia lo descrito en la [HU - 6 - Caso 1](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true)

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
La acción se habilita según el estado del cumplido.

![image](https://user-images.githubusercontent.com/73924638/215290918-a4db8881-66c6-437c-ba81-a4d246c5bebb.png)

**Comment by Mechaz123** [comment]
Al hacer el envío del cumplido aparece el mensaje de éxito y se cambia el estado del cumplido.

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
