### ISSUE TITLE
HU1 - 7 - 1 - MockUps para vista de "Aprobación Coordinador"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#41]
Con base en la vista de "Aprobación Coordinador" del sistema "Admistrativa" y en las [historias de usuario](https://docs.google.com/spreadsheets/d/1k5OZ54PjV7v8eE5nqK-rZYd-ki-a4GYM/edit#gid=1984585544), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Vista de "Revisión Coordinador".

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se adjunta el mockup relacionado a revisión coordinador.

![image](https://user-images.githubusercontent.com/73924638/214756022-0d9c232f-4e7b-45b7-849f-fd638bdb8b07.png)
