### ISSUE TITLE
HU1 - 7 - 1 - Creación menú "Revisión Coordinador"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#42]
Se requiere la creación  del menú "Aprobación Coordinador" asociado al rol de "Coordinador".

Pasos de creación:

1. Creación de menú "Aprobación Coordinador" en "CONFIGURACIÓN" asociado a CUMPLIDOS_DVE.
3. Asignación de roles "Coordinador" y "Administrador" para visualizar el menú de "Aprobación Coordinador" en "CONFIGURACIÓN".
4. Llamado de menú "Aprobación Coordinador" desde el cliente de cumplidos dve.

**Criterios de aceptación**

- [x] Creación y registro de menú "Aprobación Coordinador" en Configuración.
- [x] Pruebas de visualización del menú "Aprobación Coordinador".

Nota: [sistema Configuración en pruebas](https://pruebasconfiguracion.portaloas.udistrital.edu.co/)

**Comment by Mechaz123** [comment]
Queda en funcionamiento la opción para el perfil de coordinador.

![image](https://user-images.githubusercontent.com/73924638/216163831-3ddd42a8-24bf-4847-8adc-874faa1416bf.png)
