### ISSUE TITLE
HU1 - 7 - 1 - Desarrollo de lógica de la vista "Aprobación Coordinador"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#44]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/41) y la [vista desarrollada](https://github.com/udistrital/cumplidos_dve_cliente/issues/43), se requiere implementar lógica para vista de "Revisión Coordinador" en la cual se visualice el nombre del coordinador y todas las solicitudes de cumplidos asociadas a su cargo y su nombre.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: en este issue no se requiere el desarrollo de las acciones permitidas por solicitud.

**Comment by Mechaz123** [comment]
Se desarrolla la lógica relacionada a la vista aprobación coordinador.

![image](https://user-images.githubusercontent.com/73924638/216848464-6a5c5302-9d20-4501-b361-4ec18abe2f7b.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
