### ISSUE TITLE
HU1 - 9 - 1 - Dar visto bueno a una solicitud de cumplido de un docente.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#50]
Segun la implementación de lógica para la vista "Revisión Coordinador", se requiere adicionar la acción "Visto bueno" en el conjunto de acciones de cada solicitud de cumplido asociada al proceso de revisión de un coordinador e implementar la lógica correspondiente para aprobar dicha solicitud.

Observaciones:

1. Se debe realizar el cambio de estado de la solicitud una vez se apruebe.
2. Se requiere mostrar mensaje emergente de confirmación de aprobación de la solicitud.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 9 - 1](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true).

**Comment by Mechaz123** [comment]
Se desarrolla la lógica relacionada a la aprobación de una solicitud de cumplido.

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
