### ISSUE TITLE
HU1 - 9 - 1 - Dar visto bueno a varias solicitudes de cumplidos de docentes de forma simultanea.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#52]
Segun la implementación de lógica para la vista "Revisión Coordinador", se requiere adicionar checkbox a cada solicitud de cumplido y asociarlo con la lógica del boton "Aprobar Solicitudes", para aprobar de forma simultanea todas las solicitudes seleccionadas por el coordinador.

Observaciones:

1. Se debe realizar el cambio de estado de todas las solicitudes una vez se aprueben.
2. Se requiere mostrar mensaje emergente de confirmación de aprobación de las solicitudes.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 9 - 1](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true).

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a aprobar varios cumplidos.

![image](https://user-images.githubusercontent.com/73924638/218392059-9c82405a-e6ec-4dda-a4af-b704f9eeaac7.png)

![image](https://user-images.githubusercontent.com/73924638/218392180-ddb96c4f-29ba-40e4-8961-782920022f3c.png)

![image](https://user-images.githubusercontent.com/73924638/218392376-03cb1416-0db7-4b51-8126-0516114e5644.png)

![image](https://user-images.githubusercontent.com/73924638/218392473-735dcaa3-6b55-4be0-8e38-222464135e56.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
