### ISSUE TITLE
HU1 - 9 - 1 Creación Mockups para acciones de "Visto Bueno", "Rechazar" y "Visto bueno de varias solicitudes"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#53]
Se requieren crear Mockups para la aprobación y rechazo de solicitudes de cumplidos por parte del coordinador, de acuerdo a la siguiente lista:

1. Mockup de confirmación de visto bueno de una solicitud de cumplido.
2. Mockup de rechazo de una solicitud de cumplido.
3. Mockup de confirmación de visto bueno para varias solicitudes de cumplido.

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

Nota: tomar como referencia lo señalado en la [HU1 - 9 - 1](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true).

**Comment by Mechaz123** [comment]
Mockup de confirmación de visto bueno de una solicitud de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215608673-993063bc-8b28-4bab-8d2a-cc8b2a037025.png)

Mockup de rechazo de una solicitud de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215608446-8f454828-9942-4c89-9139-e3b1d7bcddd2.png)

Mockup de confirmación de visto bueno para varias solicitudes de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215608847-bdf929c5-e176-46b9-95e5-c0f4d2505553.png)

**Comment by Mechaz123** [comment]
Mockup de rechazo de una solicitud de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215609466-d46501ac-7b89-4a78-9b67-f4b76f445ab1.png)

![image](https://user-images.githubusercontent.com/73924638/215890766-05eb72b8-a16a-4670-a990-5a7791bee8cb.png)

Mockup de confirmación de visto bueno para varias solicitudes de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215609032-62e4b492-7a9d-480e-a1f9-2b7cb061cf70.png)

**Comment by Mechaz123** [comment]
Mockup de confirmación de visto bueno para varias solicitudes de cumplido.

![image](https://user-images.githubusercontent.com/73924638/215609032-62e4b492-7a9d-480e-a1f9-2b7cb061cf70.png)

**Comment by a52290451** [comment]
Se aprueban los mockups realizados con las siguientes observaciones:

1. Manejar en todos los avisos el concepto de "Solicitud de cumplido"
