### ISSUE TITLE
HU1 - 10 - 1 - Creación Mockup para vista "Aprobación Cumplidos" asociada a Supervisores.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#55]
Con base en las [historias de usuario](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQlv5KJIJYNfBCv_N64gm_UBITiJR3Ll6DPiAXjUwj-E9g?e=WWauMx), se requiere realizar los mockups necesarios manteniendo la paleta de colores del sistema base.

Lista de mockups:
1. Vista de "Apronbación Cumplidos" asociada a supervisores.

**Criterios de aceptación**

- [x] Creación de mockups.
- [x] Revisión  y aceptación de mockups.

**Comment by Mechaz123** [comment]
Se desarrolla la vista para la revisión del supervisor.

![image](https://user-images.githubusercontent.com/73924638/215897096-52850965-fd3d-4fac-8d9c-3e67ccc30173.png)

**Comment by a52290451** [comment]
Se aprueba mockup realizado
