### ISSUE TITLE
HU1 - 10 - 1 - Creación menú "Aprobación Supervisor"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#56]
Se requiere la creación  del menú "Aprobación Supervisor" asociado al rol de "Supervisor".

Pasos de creación:

1. Creación de menú "Aprobación Supervisor" en "CONFIGURACIÓN" asociado a CUMPLIDOS_DVE.
3. Asignación de roles "Supervisor" y "Administrador" para visualizar el menú de "Aprobación Supervisor" en "CONFIGURACIÓN".
4. Llamado de menú "Aprobación Supervisor" desde el cliente de cumplidos dve.

**Criterios de aceptación**

- [x] Creación y registro de menú "Aprobación Supervisor" en Configuración.
- [x] Pruebas de visualización del menú "Aprobación Supervisor".

Nota: [sistema Configuración en pruebas](https://pruebasconfiguracion.portaloas.udistrital.edu.co/)

**Comment by Mechaz123** [comment]
Queda en funcionamiento el menú aprobación supervisor para el perfil de SUPERVISOR.

![image](https://user-images.githubusercontent.com/73924638/221678599-ce134071-10ec-41c3-bbf5-d04ffbe699f7.png)
