### ISSUE TITLE
HU1 - 10 - 1 - Creación de vista "Aprobación Supervisor"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#57]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/55), se requiere implementar vista de "Aprobación Supervisor" en la cual se presente el nombre del supervisor y el listado de las solicitudes de cumplido que deben estar en una tabla en la parte inferior de la vista.

Adicional a esto, se requiere elaborar el boton "Aprobar cumplidos" que debe estar bloqueado en la parte inferior, despues de la tabla de solicitudes de cumplidos. 

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla la vista asociada a Aprobación Supervisor.

![image](https://user-images.githubusercontent.com/73924638/218866414-6ddc10bd-a89f-4f6e-a307-e965fee37262.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
