### ISSUE TITLE
HU1 - 10 - 1 - Desarrollo de lógica de la vista "Aprobación Supervisor"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#58]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/55) y la [vista desarrollada](https://github.com/udistrital/cumplidos_dve_cliente/issues/57), se requiere implementar lógica para vista de "Aprobación Supervisor" en la cual se visualice el nombre del Supervisor y todas las solicitudes de cumplidos asociadas a su cargo y su nombre.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: en este issue no se requiere el desarrollo de las acciones permitidas por solicitud.

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a la vista Aprobación supervisor.

![image](https://user-images.githubusercontent.com/73924638/218866006-a2fbe881-a78c-49a6-b1f8-26339aa4bbe9.png)

![image](https://user-images.githubusercontent.com/73924638/218866192-3996f337-a2c0-4321-a87a-7993e888c4ea.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
