### ISSUE TITLE
Lógica de responsable en Carga de solicitudes asociadas a un Coordinador.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#59]
Se requiere implementar lógica asociada a el coordinador responsable de reevisar las solicitudes de cumplido de un docente, de acuerdo a su implementación en administrativa_mid.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza la corrección de la lógica asociada al envío del cumplido, para los campos de responsable y cargo responsable, al momento de enviar una solicitud a revisión, se agregará el número de documento del coordinador de la dependencia y se cambiará el cargo responsable de "DOCENTE" a "COORDINADOR".

![image](https://user-images.githubusercontent.com/73924638/217366064-6fe2107c-28a3-4962-835e-4e739366120a.png)
