### ISSUE TITLE
Creación y refactor cumplidosdve_crud

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#6]
Se requieren realizar las siguientes tareas:

1. Creación de respositorio cumplidos_dve_crud.
2. Creación de crud en ambiente local con comandos de go y beego, asociado al esquema de la base de datos creada.
3. Ejecución de refactor de API, con base en fork actualizado (Juan Pablo),
4. Push en rama develop.
5. Creación de ambiente de pruebas para el crud.
6. Pull request a rama release.

**Criterios de acpetación**

- [x] Creación de repositorio.
- [x] Creación de rama develop y release.
- [x] Commit en rama develop.
- [x] Check list de despliegue en pruebas.
- [x] Pull request en rama release.
- [x] Despliegue de api en pruebas.

Nota: tener en cuenta el siguiente material de apoyo.

1. [Formato de pruebas funcionales.](https://github.com/udistrital/cumplidos_dve_cliente/files/9964140/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Cumplidos.xlsx)
2. [Formato de checklist.](https://github.com/udistrital/resoluciones_cliente/issues/80)
3. [ISSUE guía para creación de crud y mid](https://github.com/udistrital/resoluciones_crud_api/issues/9).

**Comment by Mechaz123** [comment]
Se crea el documento checklist para Cumplidos Dve Crud:
https://docs.google.com/document/d/1Qiqt4o0eZFxSrk8blubJY6FKYF0sXvPz/edit?usp=sharing&ouid=117272980466294232560&rtpof=true&sd=true

**Comment by a52290451** [comment]
Se realiza despliegue exitoso de cumplidos_dve_crud en ambiente de pruebas:

Solicitud Tuleap: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=50422
Ejecución Drone.yml: https://hubci.portaloas.udistrital.edu.co/udistrital/cumplidos_dve_crud/5

Prueba: [http://pruebasapi2.intranetoas.udistrital.edu.co:8534/](http://pruebasapi2.intranetoas.udistrital.edu.co:8533/)

![image](https://user-images.githubusercontent.com/36229498/204614341-5e285549-729d-436a-a274-5eef3f78bbe3.png)
