### ISSUE TITLE
HU1 - 11 - 1 - Aprobar una solicitud de cumplido de un docente por parte del supervisor.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#65]
Segun la implementación de lógica para la vista "Aprobación Supervisor", se requiere adicionar la acción "Aprobar" en el conjunto de acciones de cada solicitud de cumplido asociada al proceso de revisión de un Supervisor e implementar la lógica correspondiente para aprobar dicha solicitud.

Observaciones:

1. Se debe realizar el cambio de estado de la solicitud una vez se apruebe.
2. Se requiere mostrar mensaje emergente de confirmación de aprobación de la solicitud.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido.

**Criterios de aceptación**

- [ ] Creación de rama feat.
- [ ] Desarrollo en ambiente local.
- [ ] Pruebas en ambiente local.
- [ ] Commit en rama feat.
- [ ] PR en rama develop.
- [ ] Checklist de despliegue en ambiente de pruebas.
- [ ] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 11 - 1](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true).

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a aprobación supervisor para una petición de cumplido.

![image](https://user-images.githubusercontent.com/73924638/220179537-60bdd026-c6b9-4df8-ba93-87be69cca09d.png)

![image](https://user-images.githubusercontent.com/73924638/220179609-2d0883c4-b937-436b-a8ea-55f08058f351.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
