### ISSUE TITLE
HU1 - 12 - 1 & 2 - Aprobar varias solicitudes de cumplidos de docentes por parte del supervisor.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#67]
Segun la implementación de lógica para la vista "Aprobación Supervisor", se requiere adicionar checkbox a cada solicitud de cumplido y asociarlo con la lógica del boton "Aprobar Solicitudes", para aprobar de forma simultanea todas las solicitudes seleccionadas por el supervisor.

Observaciones:

1. Se debe realizar el cambio de estado de todas las solicitudes una vez se aprueben.
2. Se requiere mostrar mensaje emergente de confirmación de aprobación de las solicitudes.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido.
4. Si no se encuentran solicitudes seleccionadas, cuando se oprima el boton "Aprobar Solicitudes", se debe mostrar un mensaje de alerta.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 12 - 1&2](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BA2E46F09-2548-5F83-042B-FF37AE209BF5%7D&file=HU%201%20-%20Creaci%C3%B3n%20Cumplidos%20DVE.xlsx&action=default&mobileredirect=true).

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a aprobar varias solicitudes para aprobación supervisor.

![image](https://user-images.githubusercontent.com/73924638/220180744-db433ffb-6b14-4daa-967f-36e11892e299.png)

![image](https://user-images.githubusercontent.com/73924638/220180783-9b4720d9-b440-4376-ad73-ae9bae8193da.png)

![image](https://user-images.githubusercontent.com/73924638/220180812-5507fd95-07db-4a41-9d5c-e899e9d9413f.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
