### ISSUE TITLE
Cambiar mensajes de error por mensajes de alerta.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#68]
Se requiere ajustar mensajes de alerta en todas las vistas, de tal forma que se cambien los mensajes de error por mensajes de alerta.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realizan modificaciones a las alertas que se muestran en algunos casos en el sistema.

![image](https://user-images.githubusercontent.com/73924638/220180842-8700b85c-20d1-49a9-9ccd-2f7183a18a2f.png)

![image](https://user-images.githubusercontent.com/73924638/220181055-a68742e5-8cd0-4e05-adc7-5335559d3160.png)
