### ISSUE TITLE
Cambio de consumo de endpoints de administrativa por resoluciones v2

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#69]
Se requiere realizar el cambio de consumo de endpoints de administrativa por resoluciones v2 para consultar contratos de docentes de vinculación especial.

NOTA: consultar con Juan Pablo los detalles para mayor seguridad.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Para el caso de los controladores de academica, queda en funcionamiento CargarContratosDocente.

![image](https://user-images.githubusercontent.com/73924638/220992779-fe6781e6-eb2c-464d-af1e-e04ae701f34a.png)

Y CargarInformacionCoordinador.

![image](https://user-images.githubusercontent.com/73924638/220993945-4f2ef78d-16b8-4aaa-9f82-c53ddd4543e1.png)

**Comment by Mechaz123** [comment]
Se deja en funcionamiento el controlador llamado GetSolicitudesCoordinador.

![image](https://user-images.githubusercontent.com/73924638/221430694-b79f4b73-c744-4174-8832-d0d6dc40db15.png)

También el controlador GetSolicitudesSupervisor.

![image](https://user-images.githubusercontent.com/73924638/221430792-5bf225ec-7d01-491c-9cb4-254e632069fb.png)

También el controlador CertificacionVistoBueno, con unas pequeñas aclaraciones.

![image](https://user-images.githubusercontent.com/73924638/221431637-d7dde6b8-13b0-4532-a2f4-e1d92a93272e.png)

Y queda en funcionamiento AprobarMultiplesSolicitudes.

**Comment by Mechaz123** [comment]
Queda en funcionamiento ConsultarPagoAprobado.

![image](https://user-images.githubusercontent.com/73924638/221442068-079a4484-8b40-4011-a933-aa137aae6672.png)

**Comment by Mechaz123** [comment]
Se agrega una nueva variable de entorno:
-Name=CUMPLIDOS_DVE_CRUD_RESOLUCIONES_URL
-Value=http://pruebasapi2.intranetoas.udistrital.edu.co:8528/v1/
