### ISSUE TITLE
Creación API MID - cumplidosdve_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#7]
Se requieren realizar las siguientes tareas:

1. Creación de respositorio cumplidos_dve_mid.
2. Creación de mid en ambiente local con comandos de go y beego.
3. Push en rama develop.
4. Creación de ambiente de pruebas para el mid.
5. Pull request a rama release.

**Criterios de acpetación**

- [x] Creación de repositorio.
- [x] Creación de rama develop y release.
- [x] Commit en rama develop.
- [x] Check list de despliegue en pruebas.
- [x] Pull request en rama release.
- [x] Despliegue de API en pruebas

Nota: tener en cuenta el siguiente material de apoyo.

1. [Formato de pruebas funcionales.](https://github.com/udistrital/cumplidos_dve_cliente/files/9964140/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Cumplidos.xlsx)
2. [Formato de checklist.](https://github.com/udistrital/resoluciones_cliente/issues/80)

**Comment by a52290451** [comment]
Se requiere elaborar checklist de pruebas

**Comment by Mechaz123** [comment]
Se adjunta el documento Checklist Cumplidos Dve Mid:
https://docs.google.com/document/d/1o1MDJmVIKlAw-eDpPja06Ka1gI3V3B6E/edit?usp=sharing&ouid=117272980466294232560&rtpof=true&sd=true

**Comment by a52290451** [comment]
Se continua seguimiento del api en el checklist adjunto.

**Comment by a52290451** [comment]
Se realiza despliegue exitoso de cumplidos_dve_mid en ambiente de pruebas:

Solicitud Tuleap: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=50381
Ejecución Drone.yml: https://hubci.portaloas.udistrital.edu.co/udistrital/cumplidos_dve_mid/10

Prueba: http://pruebasapi2.intranetoas.udistrital.edu.co:8533/

![image](https://user-images.githubusercontent.com/36229498/204614699-8a0eafb4-ae5a-4b26-b6d7-67cdbef4784c.png)
