### ISSUE TITLE
HU1 - 13 - 1 - Creación menú "Aprobación Pago"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#72]
Se requiere la creación  del menú "Aprobación Pago" asociado al rol de "Ordenador del gasto".

Pasos de creación:

1. Creación de menú "Aprobación Pago" en "CONFIGURACIÓN" asociado a CUMPLIDOS_DVE.
3. Asignación de roles "Ordenador del gasto" y "Administrador" para visualizar el menú de "Aprobación Pago" en "CONFIGURACIÓN".
4. Llamado de menú "Aprobación Pago" desde el cliente de cumplidos dve.

**Criterios de aceptación**

- [x] Creación y registro de menú "Aprobación Pago" en Configuración.
- [x] Pruebas de visualización del menú "Aprobación Pago".

Nota: [sistema Configuración en pruebas](https://pruebasconfiguracion.portaloas.udistrital.edu.co/)

**Comment by Mechaz123** [comment]
Se crea el menú llamado aprobación pago para el perfil de ordenador del gasto.

![image](https://user-images.githubusercontent.com/73924638/222989263-22a223e3-4698-493f-8a1d-ea0b104d59f7.png)
