### ISSUE TITLE
HU1 - 13 - 1 - Creación de vista "Aprobación Pago"

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#73]
De acuerdo con los [mockups elaborados](https://github.com/udistrital/cumplidos_dve_cliente/issues/74), se requiere implementar la vista de "Aprobación Pago" en la cual se presente el nombre del Ordenador del Gasto y el listado de las solicitudes de cumplido que deben estar en una tabla en la parte inferior de la vista.

Tambien se deben incluir los campos: mes, año y periodo de los cumplidos asociados al Ordenador del gasto. Estos campos deben estar bloqueados hasta que se desarrolle la lógica de generar certificaciones.

Adicional a esto, se requiere elaborar el boton "Aprobar cumplidos" que debe estar bloqueado en la parte inferior, despues de la tabla de solicitudes de cumplidos. 

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla la vista asociada a aprobacion pago.

![image](https://user-images.githubusercontent.com/73924638/221686180-3d993e08-3e58-443c-a914-a3e5dcd926d9.png)
