### ISSUE TITLE
Aplicación librería UTILIDADES

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#76]
Se requiere reemplazar las funciones de consulta y envio de información en los helpers y controladores de cumplidos_dve_mid, por las dispuestas en la librería de UTILIDADES.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se aplica la librería de utilidades al código.

![image](https://user-images.githubusercontent.com/73924638/221681255-b92e39dd-ef7a-4a45-a3d8-4819408dabd9.png)

**Comment by Mechaz123** [comment]
ACLARACIONES:
1. Queda pendiente probar los controladores de certificación y también AprobaciónPagos.
2. Existe un bug en el controlador de CertificacionVistoBueno ya que se genera por el cambio a nivel de BD con respecto al estado de la solicitud.
