### ISSUE TITLE
Creación de cliente a partir de resoluciones v2

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#8]
Se requieren realizar las siguientes tareas:

1. Clonar repositorio de resoluciones v2 cliente en el [commit señalado](https://github.com/udistrital/resoluciones_cliente_v2/tree/3ecbb83c0c2933c66ed65484a3f67af9b59b9938), en local.
2. Eliminar carpeta .git y volver a crear. (oculta)
3. Crear repo con git init y asociarlo al repo de github de cumplidos_dve_cliente. (Juan Pablo)
4. Cambiar Nombre de resoluciones a cumplidosdve a todo el código.
5. Push en rama develop.
6. Creación de ambiente de pruebas para el cliente.
7. Pull request a rama release.

**Criterios de acpetación**

- [x] Clonación y adaptación de repositorio en local.
- [x] Creación de rama develop y release.
- [x] Commit en rama develop.
- [x] Check list de despliegue en pruebas.
- [x] Pull request en rama release.
- [x] Pruebas funcionales.

Nota: tener en cuenta el siguiente material de apoyo.

1. [Formato de pruebas funcionales.](https://github.com/udistrital/cumplidos_dve_cliente/files/9964140/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Cumplidos.xlsx)
2. [Formato de checklist.](https://github.com/udistrital/resoluciones_cliente/issues/80)

**Comment by Mechaz123** [comment]
Se crea el documento Checklist para Cumplidos DVE cliente:
https://docs.google.com/document/d/1ZrJQvCSIY6VfRUyD43wkmEKVMhVWZVo8/edit?usp=sharing&ouid=117272980466294232560&rtpof=true&sd=true

**Comment by a52290451** [comment]
Queda pendiente registro en WSO2

**Comment by a52290451** [comment]
Se registra en WSO2
