### ISSUE TITLE
HU1 - 15 - 2 - Rechazar el pago de una solicitud de cumplido de un docente por parte del ordenador del gasto/Decano

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#81]
Segun la implementación de lógica para la vista "Aprobación Pago", se requiere adicionar la acción "Rechazar" en el conjunto de acciones de cada solicitud de cumplido asociada al proceso de revisión de un ordenador del gasto e implementar la lógica correspondiente para rechazar dicho pago.

Observaciones:

1. Se debe realizar el cambio de estado de la solicitud de pago una vez se rechace.
2. Se requiere mostrar mensaje emergente de rechazo de la solicitud de pago.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido para pago.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 15 - 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQlv5KJIJYNfBCv_N64gm_UBITiJR3Ll6DPiAXjUwj-E9g?e=oeKWNZ).

**Comment by Mechaz123** [comment]
Se desarrolla la acción para rechazar un pago por parte del ordenador del gasto.

![image](https://user-images.githubusercontent.com/73924638/222989980-2fd7bf25-1727-4f8d-925d-b10d6cd19eea.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
