### ISSUE TITLE
Corrección de Refactor en cumplidos_dve_crud

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#83]
Se requiere corregir funciones getAll en controladores para que devuelvan arreglos vacios con la linea "[]interface{}{}" y corregir manejo de fechas, segun como esta en resoluciones_crud_v2, con su formato correspondiente.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [ ] PR en rama develop.
- [ ] Checklist de despliegue en ambiente de pruebas.
- [ ] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza el refactor de las fechas y los cambios al retornar un arreglo vacio.

![image](https://user-images.githubusercontent.com/73924638/223224744-4de4e559-0f3b-4cc6-b140-66deb31dfae4.png)
