### ISSUE TITLE
HU1 - 16 - 1 & 2 - Aprobar varias solicitudes de pago de cumplidos de docentes por parte del Ordenador del Gasto

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#87]
Segun la implementación de lógica para la vista "Aprobación Pago", se requiere adicionar checkbox a cada solicitud de cumplido y asociarlo con la lógica del boton "Aprobar Solicitudes", para aprobar de forma simultanea todas las solicitudes de pago seleccionadas por el Ordenador del Gasto.

Observaciones:

1. Se debe realizar el cambio de estado de todas las solicitudes una vez se aprueben.
2. Se requiere mostrar mensaje emergente de confirmación de aprobación de las solicitudes.
3. Se debe recargar la página y actualizar la tabla de solicitudes de cumplido.
4. Si no se encuentran solicitudes seleccionadas, cuando se oprima el boton "Aprobar Solicitudes", se debe mostrar un mensaje de alerta.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [ ] PR en rama develop.
- [ ] Checklist de despliegue en ambiente de pruebas.
- [ ] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

NOTA: tomar como referencia lo señalado en la [HU1 - 16 - 1&2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQlv5KJIJYNfBCv_N64gm_UBITiJR3Ll6DPiAXjUwj-E9g?e=ekMLYt).

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a aprobar multiples pagos.

![image](https://user-images.githubusercontent.com/73924638/224118735-85f91366-b691-47cf-9faf-42ec61aa31fe.png)

![image](https://user-images.githubusercontent.com/73924638/224118813-86f617b0-267f-418d-b3a0-50e66ef380dd.png)

![image](https://user-images.githubusercontent.com/73924638/224118900-448684e2-91ee-4cd4-abfa-92c19fc77723.png)

**Comment by Mechaz123** [comment]
Se adjunta el link de pruebas funcionales:
[https://udistritaleduco-my.sharepoint.com/❌/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBSK9WVDXo09xUjf1IR9JYOQ?e=fnG8eq)
