### ISSUE TITLE
HU1 - 8 - 3 Lógica para creación de certificación de cumplido, de acuerdo a los datos seleccionados, por parte del Coordinador.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#89]
Se requiere implementar lógica necesaria 
para construir una certificación de cumplido, de acuerdo a los datos ingresados en la vista de  "Aprobación Coordinador".

Se debe devolver un documento en PDF asociado a la certificación.

Tomar como referencia lo señalado en la [HU1 - 8 caso 3](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQlv5KJIJYNfBCv_N64gm_UBITiJR3Ll6DPiAXjUwj-E9g?e=aTQLuD) y lo implementado en otros sistemas.

La plantilla para la certificación de cumplimiento es: 
[Certificación cumplido coordinación 07_Mar_2023_12_19_56.pdf](https://github.com/udistrital/cumplidos_dve_cliente/files/10912241/Certificacion.cumplido.coordinacion.07_Mar_2023_12_19_56.pdf)

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza el desarrollo de la funcionalidad para el tema de generación de certificados dando como resultado, la generación de un PDF.

![image](https://user-images.githubusercontent.com/73924638/227987419-b1c5d58f-3e9c-497a-b666-4fd2bdbf4463.png)
