### ISSUE TITLE
Lógica de relación de parametros para Certificaciones en Aprobación Coordinador.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#91]
Se requiere relacionar los parametros requeridos para generar una certificación de cumplidos en Vista Aprobación Coordinador, de tal forma que se calcule el periodo, de acuerdo al año seleccionado.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se relaciona el periodo en base al año seleccionado por el Coordinador.

![image](https://user-images.githubusercontent.com/73924638/227987642-fbbb931f-1284-4750-a95a-30e285a67881.png)
