### ISSUE TITLE
Corregir error de paginación en las tablas de Cumplidos DVE

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#94]
Se requiere arreglar el tema de la paginación al listar los cumplidos y demás campos en los diferentes perfiles, ya que al momento que esta función se activa los botones de paso de página se encuentran muy juntos.

**NOTA:** Se debe corregir visualmente este error.

**Criterios de aceptación:**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza el cambio visual para un mejor manejo de los botones de cambio de pagina.

![image](https://user-images.githubusercontent.com/73924638/233866484-6f2558fd-f1f6-41cf-8eae-e37e1a5da2cd.png)

**Comment by a52290451** [comment]
Se requiere cargar desarrollo en ambiente de pruebas.
