### ISSUE TITLE
Corrección de respuestas en CUMPLIDOS_DVE_MID para cuando se obtiene un NULL.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#95]
El API cumplidos_dve_mid debe retornar una respuesta exitosa al obtener en el campo DATA un null, en cualquier petición o consulta que se realice. Actualmente, cuando no encuentra datos, el API retorna una alerta de error, cuando la consulta fue exitosa pero sin resultados.

**Criterios de aceptación:**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se realiza la modificación, al momento de realizar la consulta, ya no aparecerá un error, si no una advertencia informando que no se encontraron datos relacionados a ese rol.

![image](https://user-images.githubusercontent.com/73924638/233877705-b46c2f64-39c9-4dd1-a4ac-573e4a9f4bbb.png)
