### ISSUE TITLE
Ajuste de entorno de pruebas para desarrollo de pruebas funcionales.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#96]
Se requiere realizar un listado de los pasos a seguir para adecuar el ambiente de pruebas de cumplidos DVE para que se puedan realizar pruebas funcionales de todo lo implementado.

**Criterios de aceptación**

- [x] Hacer un listado de las bases de datos que se consumen en cada vista, especificando las tablas y conexiones entre tablas requeridas.
- [x] Crear un sql que contenga datos de prueba necesarios para llevar a cabo las pruebas funcionales en ambiente de pruebas.
- [x] Crear un sql de eliminación de datos que permita revertir los datos creados anteriormente.
- [x] Listar las demas acciones que sean necesarias para llevar a cabo las pruebas funcionales.
- [x] Insertar datos en bases de datos correspondientes en ambiente de pruebas.

**Comment by a52290451** [comment]
Se requiere cargar evidencia relacionada.

**Comment by Mechaz123** [comment]
[BASES DE DATOS QUE CONSUME.txt](https://github.com/udistrital/cumplidos_dve_cliente/files/11392749/BASES.DE.DATOS.QUE.CONSUME.txt)

**Comment by Mechaz123** [comment]
Se adjunta los SQL desarrollados hasta el momento para el tema de inserción y eliminación
