### ISSUE TITLE
HU1 - 14 - 1,2 & 3 Implementación de lógica en vista de "Aprobación Pago" para recibir solicitudes de creación de certificaciones de cumplidos aprobados para pago.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#97]
Se requiere implementar lógica necesaria en la vista de "Aprobación Pago" para permitir que un Ordenador del Gasto solicite una certificación de cumplidos aprobados para pago, asociada a un mes, año y periodo específico.

Segun la [HU1 - 14 casos 1 & 2](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQlv5KJIJYNfBCv_N64gm_UBITiJR3Ll6DPiAXjUwj-E9g?e=6sIwzL), se debe contemplar los casos en que el usuario no ingrese toda la información necesaria para generar el certificado o que el certificado solicitado con los datos mencionados no pueda ser generado.

**Criterios de aceptación**

- [x] Creación de rama feat.
- [x] Desarrollo en ambiente local.
- [x] Pruebas en ambiente local.
- [x] Commit en rama feat.
- [x] PR en rama develop.
- [x] Checklist de despliegue en ambiente de pruebas.
- [x] PR en rama release.
- [ ] Pruebas funcionales en ambiente de pruebas.

**Comment by Mechaz123** [comment]
Se desarrolla la validación relacionada los campos, para la generación de certificados

![image](https://user-images.githubusercontent.com/73924638/233545909-79f61b2e-88f1-4749-8e9a-4829757a6cb1.png)

**Comment by a52290451** [comment]
Se requiere cargar desarro en ambiente de pruebas.
