### ISSUE TITLE
HU1 - 14 - 1,2 & 3 - Certificados de cumplidos aprobados para pago. - PARTE 2

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#98]
Se requiere atender casos 2 y 3 de la HU1 - 14 relacionada con la generación de certificados de cumplidos aprobados para pago por parte del ordenador del gasto. 

Actualmente se encuentra desarrollado el caso 1 relacionado con el [control de error en campos requeridos](https://github.com/udistrital/cumplidos_dve_cliente/issues/97).

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama develop, tanto para el cliente como para las APIs mid y crud.

**Sub Tareas**

- [x] Implementación de lógica de control de errores y mensajes de alerta cuando el certificado seleccionado no pueda ser generado de acuerdo a validaciones internas del sistema.
- [x] Construcción de certificado de cumplidos aprobados para pago y rechazados, de acuerdo a los datos ingresados en el cliente.
- [x] Generación de certificado en PDF y visualización por parte del usuario a través  del cliente. 

**Criterios de aceptación**

- [x] Si el ordenador del gasto intenta generar el certificado de cumplidos aprobados para pago, con los datos de ingreso correctamente diligenciados, pero se encuentra una restricción interna que impide su creación, el sistema muestra un mensaje de alerta que indica la razón por la cual e certificado no pudo ser generado.
- [x] El ordenador del gasto debe poder generar un certificado de cumplidos aprobados para pago, de acuerdo a un Año, Mes y Periodo señalados.
- [x] El certificado debe ser generado y mostrado en pantalla para el usuario, y debe tener habilitada la opción para descargarlo.

**Requerimientos**

- No presenta requerimientos para su inicio.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se desarrolla la logica asociada a la generación de certificados por parte del Ordenador del Gasto, ya se encuentra en pruebas subidos los cambios.

![image](https://github.com/udistrital/cumplidos_dve_cliente/assets/73924638/088a5ee5-71c2-4363-8320-863abd81f4ff)
