### ISSUE TITLE
Pruebas funcionales del sistema en su totalidad.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_dve_cliente#99]
Se requiere realizar pruebas funcionales de todo el sistema de cumplidos_dve, cubriendo todas las HU desarrolladas a la fecha.

Actualmente todas las HU se encuentran desarrolladas a excepción de la HU1 - 14.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama develop, tanto para el cliente como para las APIs mid y crud.
- El #96 relaciona la adaptación del sistema y la creación de datos de prueba para llevar a cabo las pruebas funcionales sin inconvenientes.

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales de todo el sistema, de acuerdo con el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQ3JGkURC3tJoi5_uefqur8BkMlLUbeDSA1WptEvMGd5TA?e=VkxMWp) dispuesto.
- [x] Corrección de errores o bugs encontrados, que no requieran gran dedicación para su corrección.
- [x] Listado de bugs o errores encontrados que requieran mayor dedicación para su corrección, con una descripción de su posible solución.

**Criterios de aceptación**

- [x] Todas las funcionalidades del sistema se encuentran probadas.
- [x] Los errores que presenta el sistema se encuentran detectados y listados para su corrección.

**Requerimientos**

- [x] El Issue #96 se encuentra terminado.
- [x] La HU1 - 14 - #98 se encuentra desarrollada y lista para ser probada.

**Dependencias**

- gestor_documental_mid
- core_amazon_crud
- oikos_api
- parametros_crud
- administrativa_produccion
- servicios_homologacion_dependencias
- academica_pruebas
- financiera_produccion
- administrativa_amazon_api
- administrativa_crud_api
- cumplidos_dve_crud
- resoluciones_crud_v2

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Mechaz123** [comment]
Se realizan las pruebas al sistema, en conjunto con las funcionalidades desarrolladas con respecto a certificados y a la vez se vuelven a probar las funcionalidades ya documentadas.

[Pruebas Funcionales - CUMPLIDOS_DVE.xlsx](https://github.com/udistrital/cumplidos_dve_cliente/files/11457096/Pruebas.Funcionales.-.CUMPLIDOS_DVE.xlsx)

**Comment by a52290451** [comment]
De acuerdo con las pruebas realizadas, se genera la siguiente card con correcciones requeridas:

1. #111

**Comment by a52290451** [comment]
Queda pendiente realizar pruebas de interoperabilidad con los siguientes sitemas:

1. Resoluciones docentes V2
2. Titan_mid

**Comment by a52290451** [comment]
Se requiere adjuntar evidencia de pruebas funcionales asociadas a servicios consumidos de Resoluciones docentes V2 y replica en titan_mid.

**Comment by a52290451** [comment]
Evidencia de correcciones realizadas tras la realización de las pruebas funcionales:

#111

**Comment by Mechaz123** [comment]
Se actualizan las pruebas funcionales que se hacen respecto a titan mid y la interoperabilidad con Resoluciones V2

https://udistritaleduco-my.sharepoint.com/:x:/g/personal/daarojasg_udistrital_edu_co/ETVpQuvTwyRX8R3Cu15wBDwBpkXWOtAmxOqr9XyhpASZxQ?e=yec3AP
